export const FETCH_ALL_BLOG = "FETCH_ALL_BLOG";
export const FETCH_BLOG_ID = "FETCH_BLOG_ID";
export const FETCH_BLOG_START = "FETCH_BLOG_START";
export const DELETE_BLOG = "DELETE_BLOG";
export const FETCH_BLOG_BY_USER_ID = "FETCH_BLOG_BY_USER_ID";
export const CREATE_NEW_BLOG = "CREATE_NEW_BLOG";
export const FETCH_THIRUKKURAL_START = "FETCH_THIRUKKURAL_START";
export const FETCH_THIRUKKURAL_BY_NUMBER = "FETCH_THIRUKKURAL_BY_NUMBER";